#!/usr/bin/env python3
""" Marshal Compiler """

import sys
import scanner
import ast
import visit_c_prot
import visit_c_header
import visit_c_code

types_done = set();
cin = sys.stdin;

def main():
    """ main compiler routine """
    astree = ast.make_ast(scanner.scan(cin));
    print('/* ========= HEADERS =========== */\n')
    print(visit_c_header.generate(astree) + '\n\n');
    print('/* ========= PROTOTYPES ========= */\n')
    print(visit_c_prot.generate(astree) + '\n\n');
    print('/* ========= CODE ========= */\n')
    print(visit_c_code.generate(astree) + '\n\n');
    return 0;

if __name__ == '__main__':
    sys.exit(main());

